name: hello world
favicon: null
layout_spectrum: 0.61806
typography_spectrum: 0.2362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#fafafa'
    - '#666661'
    - '#fff15c'
    - '#adadad'
  brandStrength: 0.75
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
