name: hello world
favicon: null
layout_spectrum: 0.61806
typography_spectrum: 0.2362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8d4c8'
    - '#000000'
    - '#91928d'
    - '#6b675e'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
