name: hello world
favicon: null
layout_spectrum: 0.26646642992272973
typography_spectrum: 0.5464212403167039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9760886577423662
  lightness: 0.7684928018134087
  saturation: 0.9339732138905674
  rhythmicContrast: 0.5095183171797544
purpose: []
